version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - backend-db

  # client:
  #   build:
  #     context: ./client/
  #     dockerfile: Dockerfile
  #   command: npm start && npm run storybook
  #   ports:
  #     - "3000:3000"
  #     - "6006:6006"
  #   volumes:
  #     - ./client:/usr/src/app
  #     - /usr/src/app/node_modules

  backend-db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword


  