version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app







  